<script src="<?= url('public/js/jquery-3.5.1.min.js') ?>"></script>
<script src="<?= url('public/js/bootstrap.bundle.min.js') ?>"></script>
<script src="<?= url('public/js/owl.carousel.min.js') ?>"></script>
<script src="<?= url('public/js/jquery.magnific-popup.min.js') ?>"></script>
<script src="<?= url('public/js/smooth-scrollbar.js') ?>"></script>
<script src="<?= url('public/js/select2.min.js') ?>"></script>
<script src="<?= url('public/js/slider-radio.js') ?>"></script>
<script src="<?= url('public/js/jquery.inputmask.min.js') ?>"></script>
<script src="<?= url('public/js/plyr.min.js') ?>"></script>
<script src="<?= url('public/js/main.js') ?>"></script>